### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by igarrido-adalab** [Adalab/modulo-2-evaluacion-intermedia-maria-guerrero#1]
Really cool job @maria-guerrero !!!

Here you have some tips to improve the exercise:

### JavaScript: basic

- [x] Define the logic to make the counter work.
- [x] Use three counter variables: one for user wins, other for computer wins and another for total rounds played.
- [x] Increment the counter for user wins when the user wins a round (find the correct conditions).
- [x] Increment the counter for computer wins when the computer wins a round (find the correct conditions).
- [x] Increment the round counter always the user clicks on "Jugar" button.
- [x] Show the counters in the proper elements of the page.
- [ ] Watch out for constant names used to save DOM references... Do we want to use the DOM reference or that DOM element content (innerHTML/value)?  (look at `randomResult`, `playerResult` or `computerResult`)

### JavaScript: advanced

- [ ] Check if the `<select>` has the default option (with no value).
- [ ] Check if the round counter has reached the limit of rounds.
- [x] Move you counter logic into a function and execute it on each click.
- [ ] You are writing many times `"trackEl.innerHTML = 'something';"`, what about making a function that accepts a string as param and paints it into `'trackEl'`?

### Good practices

- [ ] Indent and avoid extra white spaces to improve readability and prevent bugs. Configurate code formatter in VS Code!!!
- [ ] Try to use imperative for functions names. (only this occurrence: <https://github.com/Adalab/modulo-2-evaluacion-intermedia-maria-guerrero/blob/26f46e766e100aba35fcbb5651c8395fc9b059a4/js/main.js#L53>
- [ ] Try to improve your commits messages. "Add JS" is a bit poor. "Add random number logic" is more explanatory.

### Structure

- [x] Link the external JS file correctly (watch the path!).
- [x] Fix position of the script tag in the HTML (it should be at the end of the `body`, but inside it).
- [x] Define a good structure of folders and files for the project.
- [x] Remove unused files/folders from the project: node_modules, package-lock.json.
- [x] CSS and JS path must to start with `./`.

### HTML

- [ ] Don't leave attributes with empty value. (Here: <https://github.com/Adalab/modulo-2-evaluacion-intermedia-maria-guerrero/blob/26f46e766e100aba35fcbb5651c8395fc9b059a4/index.html#L21>

### Steps to finish the game (for those far from the solution)

You are close to the exercise solution, but here you have a steps guide to complete it anyway ;)

1. Save a reference to DOM elements in variables.
2. Init counters of winned rounds to 0.
3. After the user clicks on the “Jugar” button, generate the random number and save it to a variable.
4. Define a function that calculates the computer selection from the random number.
5. Define other function to compare user selected option and computer generated option.

- First, one conditional to check if the user and the computer have drawn.
- Then, define one conditional for each possible case
  - if the user chose “Tijeras” and the computer generated “Papel”, user wins.
  - if the user chose “Papel” and the computer generated “Piedra”, user wins.
  - if the user chose “Piedra” and the computer generated “Tijeras”, user wins.
  - if the user chose “Tijeras” and the computer generated “Piedra”, computer wins.
  - if the user chose “Papel” and the computer generated “Tijeras”, computer wins.
  - if the user chose “Piedra” and the computer generated “Papel”, computer wins.

7. Increment the number of rounds won to which corresponds and write the result into the page.
8. Assign a listener to the button click to execute the previous function.
9. Create other function to check if the players have reached the maximum limit of rounds and call it from the listener function.

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Show an image with the user and computer selection
- Make the input work when selecting the option.
- Add a reset button that cleans the select, the counter and writes the initial feedback
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

> Do not close this issue until your teacher asks you to

**Comment by igarridomorillas** [comment]
Ok!
